### ISSUE TITLE
Bayesian optimization with Wake-T

### ISSUE THREAD

**Issue by mehdiabedi1234** [optimas-org/optimas#183]
Dear Ms/sir:
Is it possible to only have example Python files for Bayesian optimization with  Wake_T? there are in Optimas website, Optimization with FBPIC
, Optimization with HiPACE++,
 Multitask optimization with FBPIC and Wake-T, but there is no file for optimization with wake_T. If there are Python codes for Wake_T, it is useful for me to have a fasting tracking code for optimization. 
Best regards,

**Comment by AngelFP** [comment]
Hi @mehdiabedi1234 ,
thanks for pointing that out. We do have an example with Wake-T only, but it is not in the online documentation. You can find it here https://github.com/optimas-org/optimas/tree/main/examples/wake_t

It is a simple example that uses Wake-T to optimize the gradient of an active plasma lens.

**Comment by AngelFP** [comment]
I'll close this issue since the problem should be solved, but feel free to reopen if you need further assistance @mehdiabedi1234 .
