### ISSUE TITLE
Unable to run a `.py` template with a different python environment

### ISSUE THREAD

**Issue by AngelFP** [optimas-org/optimas#214]
When using a `TemplateEvaluator` with an `env_script` that loads a different python environment, libeEnsemble still tries to run the template with the optimas python.

This seems to be because the `precedent` attribute of an `Application` is set by default to the python path of the optimas environment.

What would be the best way of fixing this? By exposing the `precedent` parameter in the `TemplateEvaluator`?

**Comment by shuds13** [comment]
I think this is fixed and we can close.
