### ISSUE TITLE
Number of `Sobol` initialization is always equal or greater than `sim_workers`

### ISSUE THREAD

**Issue by delaossa** [optimas-org/optimas#220]
For all cases that I have checked (starting from scratch, resuming, adding evaluations manually, etc.), the minimum number of `Sobol` evaluations is always `sim_workers`, even if `n_init < sim_workers`, or if there is already evaluations added manually or from a previous run.
For these last cases, I would expect that the generation strategy changes to BO immediately.

**Comment by AngelFP** [comment]
Hi @delaossa , that's right. It looks like this was an issue introduced in #207. A fix is now included in #185.

**Comment by delaossa** [comment]
Excellent! Muchas gracias, Angel! ;)
