### ISSUE TITLE
Seg fault 11

### ISSUE THREAD

**Issue by SchroederSa** [optimas-org/optimas#234]
The exact same script runs using:

```
gen = GridSamplingGenerator(
    varying_parameters=variables,
    objectives=[obj],
    analyzed_parameters=[l4, k1, k2, k3, k4, k5, k6, ltot, Wx, Wy],
    n_steps=[2, 2, 2],
)
```

but crashes with Seg fault 11 when using:

```
gen = AxSingleFidelityGenerator(
    varying_parameters=variables,
    objectives=[obj],
    analyzed_parameters=[l4, k1, k2, k3, k4, k5, k6, ltot, Wx, Wy],
)
```

Any thoughts where this could be coming from?

Thank you!
Sarah

**Comment by shuds13** [comment]
@SchroederSa 
Has there been any progress on this? It may help to post your run script if that's possible.

**Comment by SchroederSa** [comment]
@shuds13, Unfortunately not. I was setting up another example where I ran into the same problem. 
I simulate a fixed-geometry quadrupole triplet (using [ocelot](https://github.com/ocelot-collab/ocelot?tab=readme-ov-file)) and find an optimal longitudinal position in the beamline. I then use optimas to vary the assembly of the triplet geometry and beam energy.

[Archive.zip](https://github.com/user-attachments/files/16956656/Archive.zip)

[ensemble.log](https://github.com/user-attachments/files/16956666/ensemble.log)
[exploration_parameters.json](https://github.com/user-attachments/files/16956667/exploration_parameters.json)
[libE_stats.txt](https://github.com/user-attachments/files/16956669/libE_stats.txt)

**Comment by SchroederSa** [comment]
A complete delete of my Miniconda and reinstallation fixed the problem.
Thanks
Sarah
