### ISSUE TITLE
Optimas exits if a history file is given, but not found

### ISSUE THREAD

**Issue by delaossa** [optimas-org/optimas#80]
Optimas exits if a history file is given, but not found.
https://github.com/optimas-org/optimas/blob/ed14c6ed3a873d250ec70f21c5a37775a62d6e4c/optimas/explorations/base.py#L133-L148
This current behaviour is problematic with my usual post processing scripts, as sometimes the optimas run script is accessed from a location that does not follow the relative path to the history file.
Previously in `libE_opt`, if the history file was not found, it would continue as if not given.

**Comment by AngelFP** [comment]
This should be solved now that #120 is merged. The recommended approach to analyze and optimas run is to use the new `ExplorationDiagnostics` class. (see https://optimas.readthedocs.io/en/latest/user_guide/basic_usage/exploration_diagnostics.html and https://optimas.readthedocs.io/en/latest/api/_autosummary/optimas.diagnostics.ExplorationDiagnostics.html#optimas.diagnostics.ExplorationDiagnostics)
