### ISSUE TITLE
Example multi_stage: warpx executable not copied in simulation directory

### ISSUE THREAD

**Issue by lucafedeli88** [optimas-org/optimas#97]
Hi everyone,

I tried to run the `multi_stage` example, but I got an error message stating that `libensemble` was not able to find the `warpx` executable (which I placed in the folder where the `run_example.py` script is located). I managed to run the example by changing the following lines in `template_evaluator.py`:

```
            executable_path = './' + self.executable
            self.sim_files.append(self.executable)
```
--->
```
            executable_path =  self.executable
            self.sim_files.append(self.executable)
```

Is it possible that `sim_files` is not actually used?

**Comment by AngelFP** [comment]
Hi @lucafedeli88, thanks for reporting this. I had a look at the example and managed to reproduce the issue.

There was an issue in how the `Exploration` was being initialized that indeed prevented the executable from actually being added to the `sim_files`.

I made a PR with the fix (#98). Would you be able to try it out (`pip install git+https://github.com/optimas-org/optimas.git@fix_executable`) and check that everything works well on your side?

**Comment by lucafedeli88** [comment]
Thanks a lot for having fixed this so quickly, @AngelFP ! It works well on my side...

**Comment by AngelFP** [comment]
Great, thanks!
